// Automatically generated by Advanced Solutions Inc. APIDevTool 2018a
// ============================================================================
// 
// A custom file header for this custom project
// 
// ============================================================================
// This file is automatically overwritten - changes will not be saved.
#ifndef __CUSTOMCOMPONENT_INIT__
#define __CUSTOMCOMPONENT_INIT__

// Visual Studio, Build Specification, for specifying in code what Visual Studio will build
#ifdef DLL_PROJECT
#define VS_PROJECT
#endif /* DLL_PROJECT */

#ifdef VS_PROJECT
#include "CustomComponent_Cond.auto.hpp"
#endif /* VS_PROJECT */

extern "C"
{
   MCDH_FUNC_EXPORT void CustomComponent_Init(void);
   MCDH_FUNC_EXPORT void CustomComponent_Destroy(void);
}

#endif /* __CUSTOMCOMPONENT_INIT__ */

