// Automatically generated by Advanced Solutions Inc. APIDevTool 2018a
// ============================================================================
// 
// A custom file header for this custom project
// 
// ============================================================================
// This Header File is for setting up INCLUDE/EXCLUDE definitions.

#ifndef __CUSTOMCOMPONENT_DEFINES__
#define __CUSTOMCOMPONENT_DEFINES__

// Look in CustomComponent_VSBS.auto.hpp to see the list of INCLUDE/EXCLUDE macro options.

#define INCLUDE_ALL_CUSTOMCOMPONENT

// By convention, in the cond files, everything is disabled by default.  With the above
// defined, everything in this .DLL has been enabled.

#endif /* __CUSTOMCOMPONENT_VSBS__ */

