// Automatically generated by Advanced Solutions Inc. APIDevTool 2018a
// ============================================================================
// 
// A custom file header for this custom project
// 
// ============================================================================

#ifndef __CUSTOMDISTURBANCE_HPP__
#define __CUSTOMDISTURBANCE_HPP__

#include "CustomDisturbance.auto.hpp"

class MCDH_CLASS_EXPORT CCustomDisturbance : public CComponentBase,
   public CIFODY_Disturbance,
   public CIFMyInterface
{
// AUTOCODE_CLASS_MACRO_CUSTOMDISTURBANCE
#define __CUSTOMDISTURBANCE_INSIDE_CLASS_AUTO_HPP__
#include "CustomDisturbance.auto.hpp"
#undef __CUSTOMDISTURBANCE_INSIDE_CLASS_AUTO_HPP__

   private:

   protected:

   public:
};

#endif /* __CUSTOMDISTURBANCE_HPP__ */

