// Automatically generated by Advanced Solutions Inc. APIDevTool 2018a
// ============================================================================
// 
// A custom file header for this custom project
// 
// ============================================================================
// This file is automatically overwritten - changes will not be saved.
#ifndef __CUSTOMCOMPONENT_COND__
#define __CUSTOMCOMPONENT_COND__

// Visual Studio, Build Specification, for specifying in code what Visual Studio will build
#include "CustomComponent_VSBS.hpp"

// Thus begins some epic preprocessor abuse

#ifdef INCLUDE_ALL_CUSTOMCOMPONENT

// define everything
#define INCLUDE_CUSTOMDISTURBANCE

#else /* ifndef INCLUDE_ALL_CUSTOMCOMPONENT */
#endif /* INCLUDE_ALL_CUSTOMCOMPONENT */

// If there are any EXCLUDEs, honor them
#ifdef EXCLUDE_CUSTOMDISTURBANCE
#undef INCLUDE_CUSTOMDISTURBANCE
#endif /* EXCLUDE_CUSTOMDISTURBANCE */

#endif /* __CUSTOMCOMPONENT_COND__ */
