// Automatically generated by Advanced Solutions Inc. MAXDevTool 2018b
// 
// ============================================================================
// 
// A custom file header for this custom project
// 
// ============================================================================
//     
// This is for the namespace NSMyNamespace

#ifndef __NS_MYNAMESPACE_HPP__
#define __NS_MYNAMESPACE_HPP__

namespace MyNamespace
{
   enum EMyEnum
   {
      E_AAA = 0,
      E_BBB = 1,
      E_CCC = 2
   };
   
   struct MyStruct {
      bool Field1;      /* none # Field1 Description */
      char Field2[128]; /* none # Field2 Description */
      MyStruct(void)
      {
         Field1 = false;
         memset(Field2,0,sizeof(Field2));
      }
   };
   
}

#endif /* __NS_MYNAMESPACE_HPP__ */
